version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pirineus
      MYSQL_DATABASE: pop_view
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - mariadb_data:/var/lib/mysql

  pop_view:
    build:
      context: .
    container_name: pop_view
    restart: unless-stopped
    ports:
      - "443:8443"
    environment:
      - PORT=8443
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=pirineus
      - DB_NAME=pop_view
    depends_on:
      - mariadb
    networks:
      - internal
    volumes:
      - ./API/ssl:/app/ssl

networks:
  internal:
    external: true

volumes:
  mariadb_data:
