version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pirineus
      MYSQL_DATABASE: pop_view
      MYSQL_USER: popview
      MYSQL_PASSWORD: pirineus
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - mariadb_data:/var/lib/mysql

  pop_view:
    build:
      context: ./API
    container_name: pop_view
    restart: unless-stopped
    ports:
      - "443:443"  
    environment:
      - PORT=443
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=pirineus
      - DB_NAME=pop_view
    depends_on:
      - mariadb
    networks:
      - internal
    volumes:
      - ./API/ssl:/app/ssl 

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  mariadb_data:
    driver: local  
