version: '3.8'

services:

  pop_view:
    build:
      context: .
    container_name: pop_view
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge