version: '3.8'

services:
  pop_view:
    build:
      context: .
    container_name: pop_view
    restart: unless-stopped
    ports:
      - "443:8443"
    environment:
      - PORT=8443
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=pirineus
      - DB_NAME=pop_view
    depends_on:
      - mariadb
    networks:
      - internal
    volumes:
      - ./ssl:/app/ssl

networks:
  internal:
    external: true

