version: '3.8'

services:
  app:
    build:
     context: .
    container_name: reservesapi
    restart: unless-stopped
    ports:
      - "3306:3306"  # HTTPS
    environment:
      - PORT=8443
    networks:
      - internal
networks:
  internal:
    name: internal
    external: true
